### ISSUE TITLE
The exact same association already exists

### ISSUE THREAD

**Issue by AndreaScorza** [ltonetwork/lto-public-chain#103]
When making an association transaction specifying an associationType ex = 1
if the association is revoked, and the same association is issued again (for same association is intended an association with the same associationType of the revoked one), then the node returns the error:
```The exact same association already exists```

**Comment by KaloyanTanev** [comment]
While I was running the e2e tests of association (and it's been at least 100 times) this never happened to me. Can you check if it still happens on your side after #109 is merged?

**Comment by AndreaScorza** [comment]
Actually i forgot to add the repeating association test case, 
you can replicate it from the python-api or from the cli,
i'll add the test case now

**Comment by AndreaScorza** [comment]
my bad, it is already there, it has the skip tag and the reference to this github issue, 
remove the skip tag from the association.feature file to execute it, 
or execute that scenario singularly from behave (to save time)
