### ISSUE TITLE
Swagger UI API Key not applied in test node

### ISSUE THREAD

**Issue by justmvg** [ltonetwork/lto-public-chain#122]
The Swagger UI shipped in (test) version 1.5.0-DIRTY does not apply the API key header to any calls that are executed via the web interface.

1. Set key via "Authorize" button
2. Execute a restricted call, like /debug/state

Expected behaviour:
I would expect --header 'X-API-Key: APIKEYHERE' to be added to the "curl" example, and the header being added to the XHR in the browser.
`curl -X GET --header 'Accept: application/json' --header 'X-API-Key: MyApiKeyHere' 'http://localhost:6869/debug/state'`

Actual behaviour:
No header is added to the example and the XHR request that does the call on the fly.
`curl -X 'GET' 'http://localhost:6869/debug/state' -H 'accept: */*'`

This results in the error
```
{
  "error": 2,
  "message": "Provided API key is not correct"
}
```

Please also note that restricted API's are commonly visualized with a padlock icon in the latest versions. This is also not the case here.

**Comment by justmvg** [comment]
The security scheme seems to be set as Bearer instead of Apikey as well.
[https://swagger.io/docs/specification/authentication/](https://swagger.io/docs/specification/authentication/)

**Comment by jasny** [comment]
Both bearer authorization and `X-API-Key` should work. However, only `X-API-Key` is accepted.
